models/user.py
from extensions import db

class User(db.Model):
    __tablename__= "users"
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(80),nullable = False, unique = False)
    sex = db.Column(db.String(10))
    email = db.Column(db.String(200),nullable = False, unique = True)
    created_at =db.Column(db.DateTime(),nullable = False, server_default=db.func.now())
    update_at =db.Column(db.DateTime(),nullable = False, server_default=db.func.now(),onupdate=db.func.now())
    
    @property
    def data(self):
        return{
            "id":self.id,
            "name":self.name,
            "sex":self.sex,
            "email":self.email
        }
        
    def save(self):
        db.session.add(self)
        db.session.commit()
        
        
    @classmethod
    def get_all(cls):
        r = cls.query.all()
        result = []
        
        for i in r:
            result.append(i.data)
        return result
    
    @classmethod
    def get_by_id(cls,id):
        return cls.query.filter(cls.id == id).first()

app.py
from flask import Flask,render_template
from config import Config
from extensions import db
from flask_migrate import Migrate
from routes import main



def create_app():
    app = Flask (__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = "mysql+pymysql://root:45851290@127.0.0.1:3306/back"
    app.config.from_object(Config)
    extensions(app) 
    register_resources(app)
    return app

def extensions(app):
        db.init_app(app)
        migrate = Migrate(app,db)


def register_resources(app):
    app.register_blueprint(main)
    

if __name__ == "__main__":
    app = create_app()
    app.run(debug=True)

controllers/user.py
from flask import request
from models.user import User
from extensions import db

def add_user_function():
    if request.method == "POST":
        name=request.form["name"]
        sex=request.form["sex"]
        email=request.form["email"]
        user = User(
            name=name,
            sex=sex,
            email=email
        )
        
        user.save()
        data = {
            "id":user.id,
            "name":user.name,
            "sex":user.sex,
            "email":user.email
        }
        return data
    
def edit_user_function(data):
    if request.method == "POST":
        data.name = request.form["name"]
        data.sex = request.form["sex"]
        data.email = request.form["email"]

        try:
            db.session.commit()
            return data 
        except Exception as e:
            db.session.rollback()
            raise e  

def delete_user_function(user):
    db.session.delete(user)
    db.session.commit()

routes.py
from flask import Blueprint, render_template, redirect, url_for
from controllers.user import add_user_function, edit_user_function, delete_user_function
import sys
from models.user import User

main=Blueprint("main",__name__) 

@main.route("/",methods=["GET"])
def home():
    data = User.get_all()
    return render_template("index.html", data=data)

@main.route("/adduser", methods = ["GET","POST"])
def add_user():
    data = add_user_function()
    print(data,file=sys.stderr) 
    return render_template("adduser.html",data=data)


@main.route("/edituser/<int:id>", methods = ["GET","POST"])
def edit_user(id):
    user = User.get_by_id()
    data = edit_user_function(user)
    return render_template("edituser.html",user=user,data=data)



@main.route("/deleteuser/<int:id>",methods=["POST"])   
def delete_user(id):
    user = User.get_by_id(id)
    print(user,file=sys.stderr)
    delete_user_function(user)
    return redirect(url_for("main.home"))

templates/adduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administración de usuarios</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/">Volver a inicio</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Agregar Usuario</li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-md-5">
                        <h2 class="mb-4 pb-2 px-md-2 text-center">Agregar Usuario</h2>
                        <form method="POST" action="/adduser">
                            <div class="mb-3">
                                <label for="name" class="form-label">Nombre Completo</label>
                                <input type="text" id="name" name="name" class="form-control" placeholder="Nombre Completo" required>
                            </div>
                            <div class="mb-3">
                                <label for="sex" class="form-label">Sexo</label>
                                <input type="text" id="sex" name="sex" class="form-control" placeholder="Sexo" required>
                            </div>
                            <div class="mb-3">
                                <label for="email" class="form-label">Correo Electrónico</label>
                                <input type="email" id="email" name="email" class="form-control" placeholder="nombre@email.com" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/edituser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administración de usuario</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/">Volver a inicio</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Editar Usuario</li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-md-5">
                        <h2 class="mb-4 pb-2 px-md-2 text-center">Editar Usuario</h2>
                        <form method="POST" action="/edituser">
                            <div class="mb-3">
                                <label for="name" class="form-label">Nombre Completo</label>
                                <input type="text" id="name" name="name" class="form-control" placeholder="{{ user.name }}" required>
                            </div>
                            <div class="mb-3">
                                <label for="sex" class="form-label">Sexo</label>
                                <input type="text" id="sex" name="sex" class="form-control" placeholder="{{ user.sex }}" required>
                            </div>
                            <div class="mb-3">
                                <label for="email" class="form-label">Correo Electrónico</label>
                                <input type="email" id="email" name="email" class="form-control" placeholder="{{ user.email }}" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-success">Guardar Cambios</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administracion de usuario</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script>
      function confirmDelete(user_id){
        var confirmation = confirm ("Estas seguro que queres borrar?")
        if(confirmation){
          var form = document.createElement("form");
          form.method = "POST";
          form.action = "/deleteuser" +user_id;
          document.body.appendChild(form);
          form.submit();
        }
      }
    </script>
</head>
<body>
  <div class="my-5 text-center">
      <a href="{{ url_for('main.add_user') }}" class="btn btn-primary text-white">Agregar usuario</a>
  </div>

  <br>

  <div class="w-70 d-flex p-5">
      <table class="table">
          <thead>
              <tr>
                  <th scope="col">Id</th>
                  <th scope="col">Name</th>
                  <th scope="col">Genero</th>
                  <th scope="col">Email</th>
                  <th>Action</th>
              </tr>
          </thead>
          <tbody>
              {% for item in data %}
              <tr>
                  <th scope="row">{{ item.id }}</th>
                  <td>{{ item.name }}</td>
                  <td>{{ item.sex }}</td>
                  <td>{{ item.email }}</td>
                  <td>
                      <a href="/edituser/{{ item.id }}" class="btn btn-success">Edit</a>
                      <button class="btn btn-danger" type="button" onclick="confirmDelete('{{ item.id }}')">Delete</button>
                  </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>
</html>